version: "3.7"

services:
  webserver:
    build: ./backend/
    # image: webserver:latest
    container_name: webserver
    ports:
      - "80:80"
    
  db:
    build: ./postgres/
    # image: postgres
    container_name: postgres
    environment:
      - "POSTGRES_PASSWORD=password"
      # - "DATABASE_HOST=db"
      # - "DATABASE_PORT=5432"
      # - "DATABASE_USER=postgres"
      # - "DATABASE_PASSWORD=mysecretpassword1234"
      # - "PGPASSWORD=mysecretpassword1234"
      # - "DATABASE_NAME=testdb"
    ports:
      - "5432:5432"
